version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    image: app
    ports:
      - "5050:5050"

volumes:
 data:
